language: go
go:
  - 1.9
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install --force
  - dep ensure
script:
  - go build ./...
  - go test -tags="integration" ./...
  - gometalinter.v2 --config=.gometalinter.json --deadline=1000s --vendor ./...
