language: go
go:
  - 1.9
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --force
  - dep ensure
script:
  - go build ./...
  - go test ./...
  - gometalinter --config=.gometalinter.json --deadline=1000s ./...
