version: '3'
services:
    backend:
        build:
            context: ../../app
        environment:
            YAPTIDE_BACKEND_PORT: "80"
            YAPTIDE_BACKEND_PUBLIC_URL: "backend:8001"
            YAPTIDE_DB_URL: "mongodb://test_user:test_password@mongo:27017/admin"
        ports:
            - "8001:80"
        depends_on:
            - mongo
    frontend:
        build:
            context: ../../builder
            args:
                YAPTIDE_FRONTEND_PORT: "80"
                YAPTIDE_FRONTEND_PUBLIC_URL: "localhost:8002"
                YAPTIDE_BACKEND_PUBLIC_URL: "localhost:8001"
        ports:
            - "8002:80"
    mongo:
        image: mongo:latest
        container_name: yaptide_db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "test_user"
            MONGO_INITDB_ROOT_PASSWORD: "test_password"
            MONGO_INITDB_DATABASE: "admin"



    

