package specs

// SimulationOptions ...
type SimulationOptions struct {
	// AntyparticleCorrectionOn ...
	AntyparticleCorrectionOn bool
	// NuclearReactionsOn ...
	NuclearReactionsOn bool
	// MeanEnergyLoss ...
	MeanEnergyLoss Fraction
	// MinEnergyLoss ...
	MinEnergyLoss float64
	// ScatteringType ...
	ScatteringType ScatteringType
	// EnergyStraggling ...
	EnergyStraggling EnergyStragglingType
	// FastNeutronTransportOn ...
	FastNeutronTransportOn bool
	// LowEnergyNeutronCutOff ...
	LowEnergyNeutronCutOff float64
	// NumberOfGeneratedParticles ...
	NumberOfGeneratedParticles int64
}

// DefaultOptions ...
var DefaultOptions = SimulationOptions{}

// ScatteringType ...
type ScatteringType int64

const (
	// NoScattering ...
	NoScattering ScatteringType = iota
	// GaussianScattering ...
	GaussianScattering
	// MoliereScattering ...
	MoliereScattering
)

// EnergyStragglingType ...
type EnergyStragglingType int64

const (
	// NoEnergyStraggling ...
	NoEnergyStraggling EnergyStragglingType = iota
	// VavilovStraggling ...
	VavilovStraggling
	// GaussianStraggling ...
	GaussianStraggling
)
